Identity Card
digitalbazaar/bedrock-angular-card-displayer pull request #2
Opened 2017-05-23 16:18 UTC by gannan08

2017-05-23 16:30 UTC, mattcollier requested changes

2017-05-23 16:30 UTC, mattcollier commented on identity-card-credential-displayer.js
> +      jsonld.promises.frame(
The current pattern is to wrap things that return a `Promise` in a `$q` style promise by wrapping with `$q.resolve(...)`

When this is done, there is no need to add `$scope.$apply()` anywhere in the promise chain.

2017-05-23 16:30 UTC, mattcollier commented on identity-card-credential-displayer.js
> +          $scope.$apply();
This can be removed if `$q.resolve()` is used as noted above.

2017-05-23 16:30 UTC, mattcollier commented on identity-card-credential-displayer.js
> +    return jsonld.promises.compact(documentTypeId, DISPLAY_CONTEXT, {
$q.resolve

2017-05-30 18:31 UTC, dlongley approved these changes
We need to do something about the monolithic design here sometime in the future, but ... that's not now. :)

Ideally we'd have separate Web Components for each credential displayer in the future ... and they could potentially draw on some common core code as well, since I'm seeing a lot of repeated boilerplate.

That said, we need what's here now, so let's move forward and plan to fix things up in the future.

2017-05-30 19:08 UTC, merged